trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: UseNode@1
  inputs:
    version: '20.x'
  displayName: 'Install Node.js'

- script: npm install -g @vscode/vsce
  displayName: 'Install vsce'

- script: |
    cd vscode-extension
    vsce package
  displayName: 'Package extension'

- script: |
    cd vscode-extension
    vsce publish \
      --packagePath *.vsix \
      --azure-credential \
      --serviceConnection CRP-COMPLY-SCAN
  displayName: 'Publish extension using Managed Identity'
